

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UnitConversor(object):
    def setupUi(self, UnitConversor):
        UnitConversor.setObjectName("UnitConversor")
        UnitConversor.resize(503, 274)
        self.centralwidget = QtWidgets.QWidget(UnitConversor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(228, 50, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 50, 101, 20))
        self.label_4.setObjectName("label_4")
        UnitConversor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UnitConversor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        UnitConversor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UnitConversor)
        self.statusbar.setObjectName("statusbar")
        UnitConversor.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(UnitConversor)
        self.actionInfo.setObjectName("actionInfo")
        self.actionClose = QtWidgets.QAction(UnitConversor)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionInfo)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(UnitConversor)
        QtCore.QMetaObject.connectSlotsByName(UnitConversor)

    def retranslateUi(self, UnitConversor):
        _translate = QtCore.QCoreApplication.translate
        UnitConversor.setWindowTitle(_translate("UnitConversor", "Unit Conversor"))
        self.label.setText(_translate("UnitConversor", "TdD Unit Conversor"))
        self.comboBox_3.setItemText(0, _translate("UnitConversor", "--"))
        self.comboBox_3.setItemText(1, _translate("UnitConversor", "Distance"))
        self.comboBox_3.setItemText(2, _translate("UnitConversor", "Area"))
        self.comboBox_3.setItemText(3, _translate("UnitConversor", "Volume"))
        self.comboBox_3.setItemText(4, _translate("UnitConversor", "Mass"))
        self.comboBox_3.setItemText(5, _translate("UnitConversor", "Angle"))
        self.comboBox_3.setItemText(6, _translate("UnitConversor", "Pressure"))
        self.comboBox_3.setItemText(7, _translate("UnitConversor", "Temperature"))
        self.comboBox_3.setItemText(8, _translate("UnitConversor", "Speed"))
        self.comboBox_3.setItemText(9, _translate("UnitConversor", "Energy"))
        self.comboBox_3.setItemText(10, _translate("UnitConversor", "Power"))
        self.comboBox_3.setItemText(11, _translate("UnitConversor", "Data"))
        self.comboBox_3.setItemText(12, _translate("UnitConversor", "Currency"))
        self.label_4.setText(_translate("UnitConversor", "Conversion Type"))
        self.menuFile.setTitle(_translate("UnitConversor", "File"))
        self.actionInfo.setText(_translate("UnitConversor", "Info"))
        self.actionClose.setText(_translate("UnitConversor", "Close"))
